title: 'Bloggy'

theme: "github.com/adityatelange/hugo-PaperMod"

module:
  imports:
    path: "github.com/adityatelange/hugo-PaperMod"

baseURL: "https://blog.aleemahamed.site"

params:
  ShowBreadCrumbs: true
  ShowToc: true
  TocOpen: true
  ShowShareButtons: true
  ShowReadingTime: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
